language: c # vala
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:vala-team/ppa
  - sudo apt-get update -qq
install: ./ci_install.sh
script: ./ci_build.sh
env:
  - VALAC=valac-0.18
  - VALAC=valac-0.16
