name: Build

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Meson
      run: sudo apt update -qq && sudo apt install --no-install-recommends -y build-essential meson ninja-build
    - name: Install dependencies
      run: |
        sudo apt install --no-install-recommends -y \
          gir1.2-glib-2.0 \
          gir1.2-gee-0.8 \
          gobject-introspection \
          libfcgi-dev \
          libfcgi-bin \
          libfcgi0ldbl \
          libgee-0.8-dev \
          libgirepository1.0-dev \
          gcc \
          valac \
          && valac --version
    - name: Setup project
      run: meson setup build
    - name: Build project
      run: meson compile -C build
